apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueprint-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: blueprint-service
        image: blueprint-service:dev
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
