apiVersion: v1
kind: ConfigMap
metadata:
  name: blueprint-service-config
  labels:
    app: blueprint-service
data:
  Blueprint__ServiceName: "BlueprintService"
  Blueprint__RetryAttempts: "3"
  Blueprint__RequestTimeout: "00:00:30"
  Blueprint__MaxConcurrentRequests: "100"
  Database__CommandTimeout: "30"
  Database__MaxPoolSize: "100"
  Database__ConnectionIdleTimeout: "00:05:00"
