apiVersion: v1
kind: Secret
metadata:
  name: blueprint-db-credentials
  labels:
    app: blueprint-service
type: Opaque
data:
  # Base64 encoded PostgreSQL connection string
  # This is a placeholder; actual secrets should be managed properly in a production environment
  connection-string: SG9zdD1wb3N0Z3JlczsgUG9ydD01NDMyOyBEYXRhYmFzZT1ibHVlcHJpbnRzOyBVc2VybmFtZT1wb3N0Z3JlczsgUGFzc3dvcmQ9cG9zdGdyZXM7
